package main

import (
	"fmt"
	"hyperion/internal/bitboard"
	"os"
)

var randomState uint64 = 1804289383

func random64() uint64 {
	randomState ^= randomState >> 12
	randomState ^= randomState << 25
	randomState ^= randomState >> 27
	return randomState
}

func random64Fewbits() uint64 {
	return random64() & random64() & random64()
}

func maskRook(sq int) bitboard.Bitboard {
	var mask bitboard.Bitboard
	r, f := sq/8, sq%8
	for tr := r + 1; tr <= 6; tr++ {
		mask.Set(tr*8 + f)
	}
	for tr := r - 1; tr >= 1; tr-- {
		mask.Set(tr*8 + f)
	}
	for tf := f + 1; tf <= 6; tf++ {
		mask.Set(r*8 + tf)
	}
	for tf := f - 1; tf >= 1; tf-- {
		mask.Set(r*8 + tf)
	}
	return mask
}

func maskBishop(sq int) bitboard.Bitboard {
	var mask bitboard.Bitboard
	r, f := sq/8, sq%8
	for tr, tf := r+1, f+1; tr <= 6 && tf <= 6; tr, tf = tr+1, tf+1 {
		mask.Set(tr*8 + tf)
	}
	for tr, tf := r+1, f-1; tr <= 6 && tf >= 1; tr, tf = tr+1, tf-1 {
		mask.Set(tr*8 + tf)
	}
	for tr, tf := r-1, f+1; tr >= 1 && tf <= 6; tr, tf = tr-1, tf+1 {
		mask.Set(tr*8 + tf)
	}
	for tr, tf := r-1, f-1; tr >= 1 && tf >= 1; tr, tf = tr-1, tf-1 {
		mask.Set(tr*8 + tf)
	}
	return mask
}

func attackRookSlow(sq int, block bitboard.Bitboard) bitboard.Bitboard {
	var attacks bitboard.Bitboard
	r, f := sq/8, sq%8
	for tr := r + 1; tr <= 7; tr++ {
		attacks.Set(tr*8 + f)
		if block.Has(tr*8 + f) {
			break
		}
	}
	for tr := r - 1; tr >= 0; tr-- {
		attacks.Set(tr*8 + f)
		if block.Has(tr*8 + f) {
			break
		}
	}
	for tf := f + 1; tf <= 7; tf++ {
		attacks.Set(r*8 + tf)
		if block.Has(r*8 + tf) {
			break
		}
	}
	for tf := f - 1; tf >= 0; tf-- {
		attacks.Set(r*8 + tf)
		if block.Has(r*8 + tf) {
			break
		}
	}
	return attacks
}

func attackBishopSlow(sq int, block bitboard.Bitboard) bitboard.Bitboard {
	var attacks bitboard.Bitboard
	r, f := sq/8, sq%8
	for tr, tf := r+1, f+1; tr <= 7 && tf <= 7; tr, tf = tr+1, tf+1 {
		attacks.Set(tr*8 + tf)
		if block.Has(tr*8 + tf) {
			break
		}
	}
	for tr, tf := r+1, f-1; tr <= 7 && tf >= 0; tr, tf = tr+1, tf-1 {
		attacks.Set(tr*8 + tf)
		if block.Has(tr*8 + tf) {
			break
		}
	}
	for tr, tf := r-1, f+1; tr >= 0 && tf <= 7; tr, tf = tr-1, tf+1 {
		attacks.Set(tr*8 + tf)
		if block.Has(tr*8 + tf) {
			break
		}
	}
	for tr, tf := r-1, f-1; tr >= 0 && tf >= 0; tr, tf = tr-1, tf-1 {
		attacks.Set(tr*8 + tf)
		if block.Has(tr*8 + tf) {
			break
		}
	}
	return attacks
}

func set2bb(index int, bits int, mask bitboard.Bitboard) bitboard.Bitboard {
	var b bitboard.Bitboard
	for i := 0; i < bits; i++ {
		sq := mask.PopLSB()
		if (index & (1 << i)) != 0 {
			b.Set(sq)
		}
	}
	return b
}

func findMagic(sq int, isRook bool) uint64 {
	var mask bitboard.Bitboard
	if isRook {
		mask = maskRook(sq)
	} else {
		mask = maskBishop(sq)
	}

	bitsCount := mask.PopCount()
	numOccupancies := 1 << bitsCount
	occupancies := make([]bitboard.Bitboard, numOccupancies)
	attacks := make([]bitboard.Bitboard, numOccupancies)

	for i := 0; i < numOccupancies; i++ {
		occupancies[i] = set2bb(i, bitsCount, mask)
		if isRook {
			attacks[i] = attackRookSlow(sq, occupancies[i])
		} else {
			attacks[i] = attackBishopSlow(sq, occupancies[i])
		}
	}

	shift := 64 - bitsCount

	for {
		magic := random64Fewbits()

		used := make([]bitboard.Bitboard, numOccupancies)
		fail := false

		for i := 0; i < numOccupancies; i++ {
			magicIndex := (uint64(occupancies[i]) * magic) >> shift
			if used[magicIndex] == bitboard.Empty {
				used[magicIndex] = attacks[i]
			} else if used[magicIndex] != attacks[i] {
				fail = true
				break
			}
		}

		if !fail {
			return magic
		}
	}
}

func main() {
	fmt.Println("Generating magics...")

	f, err := os.Create("internal/magic/magics_table.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "package magic")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Auto-generated by cmd/magics/main.go")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var RookMagics = [64]uint64{")
	for sq := 0; sq < 64; sq++ {
		magic := findMagic(sq, true)
		fmt.Fprintf(f, "\t0x%016x,\n", magic)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "var BishopMagics = [64]uint64{")
	for sq := 0; sq < 64; sq++ {
		magic := findMagic(sq, false)
		fmt.Fprintf(f, "\t0x%016x,\n", magic)
	}
	fmt.Fprintln(f, "}")

	fmt.Println("Done generating magics.")
}
